pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                script{
                    echo "build stage"
                }
            }

        }
        stage('test'){
            steps{
                script{
                    echo "test stage"
                }
            }

        }

         stage('deploy'){
            steps{
                script{
                    echo "deploy stage"
                }
            }

        }
    }
}